name: trainer_promoter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

# firebase dependencies
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_functions: ^4.0.5
  loading_animation_widget: ^1.2.0+3
  flutterfire_ui: ^0.4.3+11
  go_router: ^5.0.3
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  flutter_riverpod: ^2.1.1
  google_sign_in: ^5.4.2



  #state management
  flutter_bloc: ^8.1.1
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.3.0
  nb_utils: ^4.6.25

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
#default flutter 2.5 skeleton linting.... duh....
  flutter_lints: ^2.0.1

  #guess what this package does...  
  change_app_package_name: ^1.1.0
  #flutter pub run change_app_package_name:main com.new.package.name
  
  #generate app launcher icons
  flutter_launcher_icons: ^0.11.0
  #flutter pub run flutter_launcher_icons:main


  #code generation
  freezed: ^2.1.1
  # auto_route_generator: ^4.2.0
  # hive_generator: ^1.1.2
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  # flutter pub run build_runner watch --delete-conflicting-outputs
  # flutter pub run build_runner build --delete-conflicting-outputs

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/

flutter_icons:
  image_path: "assets/icon/logo.png"
  android: true 
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/icon/logo.png" 
  remove_alpha_ios: true

